const cp_cards = [
  {
    stage: "mobilization",
    side: "cp",
    card_number: "1",
    _id: "cp1",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    war_status: "2",
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Guns of August",
    text:
      "May only be played in the first Action Round of the August 1914 turn. The Liege fort is destroyed. Place the GE 1st and 2nd Armies in the Liege space. The GE 1st, 2nd, and 3rd Armies are activated for Combat.",
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "2",
    _id: "cp2",
    ops: "2",
    sr: "2",
    combat_card: true,
    removed_after_play: true,
    rep_ge: "1",
    title: "Wireless Intercepts",
    text:
      "A GE Flank Attack Attempt vs. a space containing only RU units is automatically successful.",
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "3",
    _id: "cp3",
    ops: "2",
    sr: "2",
    combat_card: true,
    rep_ge: "1",
    title: "Von Francois",
    text: "A GE attack vs. RU units adds a +1 drm.",
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "4",
    _id: "cp4",
    ops: "2",
    sr: "2",
    combat_card: true,
    rep_ge: "1",
    title: "Severe Weather",
    text:
      "Defending units in a mountain space in Fall/Winter or a swamp space in Spring/Fall get a +2 drm.",
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "5",
    _id: "cp5",
    ops: "2",
    sr: "2",
    removed_after_play: true,
    rep_ge: "1",
    title: "Landwehr",
    text:
      "CP player receives 2 extra RPs to immediately flip reduced strength units to their full side. They may not be spent to replace eliminated units.",
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "6",
    _id: "cp6",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Entrench",
    text:
      "Place a Level 1 Trench in any space occupied by a supplied friendly Army. Both players may now Entrench.",
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "7",
    _id: "cp7",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "German Reinforcements",
    text: "9th Army.",
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "8",
    _id: "cp8",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Race to the Sea",
    text: "CP units may now end movement in Ostend, Calais, and Amiens.",
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "9",
    _id: "cp9",
    ops: "4",
    sr: "4",
    removed_after_play: true,
    war_status: "1",
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "Reichstag Truce",
    text:
      "May not be played after CP War Commitment Level is Total War. Add 1 VP.",
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "10",
    _id: "cp10",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "SUD Army",
    text:
      "Up to 2 GE corps may stack with any 1 AH unit and be Activated as a single nationality. A different stack may be chosen each Action Round.",
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "11",
    _id: "cp11",
    ops: "2",
    sr: "2",
    removed_after_play: true,
    war_status: "1",
    rep_ge: "1",
    title: "Oberost",
    text:
      "German units may now attack spaces containing RU forts. (They may always besiege such spaces.)",
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "12",
    _id: "cp12",
    ops: "4",
    sr: "4",
    removed_after_play: true,
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "German Reinforcements",
    text: "10th Army, 2 corps.",
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "13",
    _id: "cp13",
    ops: "4",
    sr: "4",
    removed_after_play: true,
    war_status: "2",
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "Falkenhayn",
    text:
      ' May only be played on Aug/Sep 1914 turns only after the"Moltke"is played or without restriction beginning in Fall 1914. Cancels the effects of"Moltke". Allows play of"Place of Execution"',
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "14",
    _id: "cp14",
    ops: "4",
    sr: "4",
    removed_after_play: true,
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "Austria",
    text: "Hungary Reinforcements  7th Army, 2 corps.",
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "56",
    _id: "cp56",
    ops: "2",
    sr: "2",
    combat_card: true,
    removed_after_play: true,
    rep_ge: "1",
    title: "Withdrawal",
    text:
      "Defending units negate one required Corps step loss and instead retreat 1 space. This also cancels any retreat caused by losing the combat. If no Corps step(s) lost, an Army step loss may be negated.",
    deck: "box",
  },
  {
    stage: "mobilization",
    side: "cp",
    card_number: "57",
    _id: "cp57",
    ops: "3",
    sr: "4",
    combat_card: true,
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Kaisertreu",
    text: "An AH attack or defence adds +1drm.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "15",
    _id: "cp15",
    ops: "2",
    sr: "2",
    combat_card: true,
    removed_after_play: true,
    rep_ge: "1",
    title: "Chlorine Gas",
    text: "A GE attack adds +1 drm.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "16",
    _id: "cp16",
    ops: "2",
    sr: "2",
    combat_card: true,
    removed_after_play: true,
    rep_ge: "1",
    title: "Liman Von Sanders",
    text: "A TU attack or defense adds a +1 drm.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "17",
    _id: "cp17",
    ops: "2",
    sr: "2",
    removed_after_play: true,
    rep_ge: "1",
    title: "Mata Hari",
    text:
      "CP player may examine all cards in the Allied player's hand and then conduct Operations using this card.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "18",
    _id: "cp18",
    ops: "2",
    sr: "2",
    combat_card: true,
    rep_ge: "1",
    title: "Fortified Machine Guns",
    text: "A GE entrenched defender adds a +1 drm.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "19",
    _id: "cp19",
    ops: "2",
    sr: "2",
    combat_card: true,
    removed_after_play: true,
    rep_ge: "1",
    title: "Flamethrowers",
    text: "A GE attack adds +1 drm.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "20",
    _id: "cp20",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Austria",
    text: "Hungary Reinforcements  10th Army.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "21",
    _id: "cp21",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "German Reinforcements",
    text: "11th Army, 1 corps.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "22",
    _id: "cp22",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "German Reinforcements",
    text: "12th Army, 1 corps.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "23",
    _id: "cp23",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Austria",
    text: "Hungary Reinforcements  11th Army.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "24",
    _id: "cp24",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Libyan Revolt (TU Reinforcements)",
    text:
      "(May only be played if there are no Allied units in the Libya space.) Place the SN unit in Libya.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "25",
    _id: "cp25",
    ops: "4",
    sr: "4",
    removed_after_play: true,
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "High Seas Fleet",
    text:
      ' High Seas Fleet sorties. Unless the Allied player plays the"Grand Fleet"as his next action, add 1 VP.',
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "26",
    _id: "cp26",
    ops: "4",
    sr: "4",
    combat_card: true,
    removed_after_play: true,
    war_status: "1",
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "Place of Execution",
    text:
      ' May only be played after the"Falkenhayn"and before the"HL Take Command". An attack vs. FR fort space adds a +2 drm.',
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "27",
    _id: "cp27",
    ops: "4",
    sr: "4",
    removed_after_play: true,
    war_status: "1",
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "Zeppelin Raids",
    text:
      "Subtract 4 BR RPs (down to 0) during the Replacement Phase of this turn.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "28",
    _id: "cp28",
    ops: "4",
    sr: "4",
    removed_after_play: true,
    war_status: "1",
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "Tsar Takes Command",
    text:
      ' May only be played if the Russian Capitulation marker is in the"Tsar Takes Command Allowed"box.',
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "29",
    _id: "cp29",
    ops: "2",
    sr: "2",
    removed_after_play: true,
    rep_ge: "1",
    title: "11th Army",
    text:
      "The GE 11th Army (only) may freely stack with any CP corps and be treated as 1 unit for Activation purposes.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "30",
    _id: "cp30",
    ops: "2",
    sr: "2",
    combat_card: true,
    rep_ge: "1",
    title: "Alpenkorps",
    text: "A GE attack to or from a mountain space adds +1 drm.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "31",
    _id: "cp31",
    ops: "3",
    sr: "4",
    combat_card: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Kemal",
    text:
      "A TU defender with a combat factor of 1 or more may fire on the Army Table. May only be used in one Combat per turn.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "32",
    _id: "cp32",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    war_status: "1",
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "War in Africa",
    text:
      "Permanently remove 1 BR corps from the game or add 1 VP (Allied choice).",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "33",
    _id: "cp33",
    ops: "5",
    sr: "5",
    removed_after_play: true,
    war_status: "1",
    rep_ah: "3",
    rep_bu: "1",
    rep_ge: "4",
    rep_tu: "2",
    title: "Walter Rathenau",
    text: "Add 1 extra GE RP during the Replacement Phase of every turn.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "34",
    _id: "cp34",
    ops: "5",
    sr: "5",
    removed_after_play: true,
    war_status: "1",
    rep_ah: "3",
    rep_ge: "4",
    rep_tu: "2",
    title: "Bulgaria",
    text: "Bulgaria joins the CP.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "58",
    _id: "cp58",
    ops: "2",
    sr: "2",
    rep_ge: "1",
    title: "Stavka Timidity",
    text:
      ' May be played after"Tsar Takes Command". No RU attacks vs. entrenched GE units (only) the rest of this turn. Mixed CP stacks may be attacked.',
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "59",
    _id: "cp59",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Polish Restoration",
    text:
      "May be played if the CP currently controls Warsaw. Subtract 1 VP. Add the three Polish Corps to the CP Reserve Box. These Corps are treated as German for all purposes but may not be relpaced if Warsaw is Allied.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "60",
    _id: "cp60",
    ops: "3",
    sr: "4",
    combat_card: true,
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Turk Determination",
    text:
      "A TU Defender in any nontrench space is considered at Trench Level 1 for all purposes for that combat only.",
    deck: "box",
  },
  {
    stage: "limited_war",
    side: "cp",
    card_number: "61",
    _id: "cp61",
    ops: "4",
    sr: "4",
    removed_after_play: true,
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "Haig",
    text:
      "Entrenched GE units in France/Belgium/Germany may ignore all retreat results vs. attacks with BR units this turn. No effect after play of Michel, Blucher, Peace Offensive.",
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "35",
    _id: "cp35",
    ops: "2",
    sr: "2",
    combat_card: true,
    removed_after_play: true,
    rep_ge: "1",
    title: "Mustard Gas",
    text: "A GE attack adds a +1 drm.",
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "36",
    _id: "cp36",
    ops: "2",
    sr: "2",
    removed_after_play: true,
    war_status: "2",
    rep_ge: "1",
    title: "U",
    text:
      'Boats Unleashed  May only be played after"HL Take Command". Subtract 1 BR RP during the Repl. Phase of each turn and prevent play of US Reinforcements until"Convoy"is played.',
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "37",
    _id: "cp37",
    ops: "2",
    sr: "2",
    removed_after_play: true,
    war_status: "1",
    rep_ge: "1",
    title: "Hoffman",
    text:
      ' May only be played after"HL Take Command". Adds +1 to all future CP Mandated Offensive die rolls.',
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "38",
    _id: "cp38",
    ops: "2",
    sr: "2",
    removed_after_play: true,
    rep_ge: "1",
    title: "German Reinforcements",
    text: "2 corps.",
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "39",
    _id: "cp39",
    ops: "2",
    sr: "2",
    removed_after_play: true,
    rep_ge: "1",
    title: "German Reinforcements",
    text: "2 corps.",
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "40",
    _id: "cp40",
    ops: "3",
    sr: "4",
    combat_card: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Air Superiority",
    text: "A GE attack adds +1 drm.",
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "41",
    _id: "cp41",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "German Reinforcements",
    text: "14th Army.",
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "42",
    _id: "cp42",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Turkish Reinforcements",
    text: "YLD Army.",
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "43",
    _id: "cp43",
    ops: "3",
    sr: "4",
    combat_card: true,
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Von Below",
    text: "Cancels all trench effects for 1 attack against only IT unit(s).",
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "44",
    _id: "cp44",
    ops: "3",
    sr: "4",
    combat_card: true,
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Von Hutier",
    text:
      "Attacker fires first and cancels all trench effects for an attack against RU unit(s).",
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "45",
    _id: "cp45",
    ops: "4",
    sr: "4",
    removed_after_play: true,
    war_status: "1",
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "Treaty of Brest Litovsk",
    text:
      ' May only be played after"Bolshevik Revolution". RU units may no longer attack. CP units may not attack RU units except TU units may attack on the Near East map. Also see 5.5.2.',
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "46",
    _id: "cp46",
    ops: "4",
    sr: "4",
    removed_after_play: true,
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "German Reinforcements",
    text: "17th Army, 18th Army.",
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "47",
    _id: "cp47",
    ops: "4",
    sr: "4",
    removed_after_play: true,
    war_status: "1",
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "French Mutiny",
    text:
      "Effects of Mandated FR Offensives are reversed. If any FR units not stacked with US units attack on a FR MO turn, add 1 VP.",
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "48",
    _id: "cp48",
    ops: "4",
    sr: "4",
    removed_after_play: true,
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "Turkish Reinforcements",
    text: "AoI Army.",
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "49",
    _id: "cp49",
    ops: "4",
    sr: "4",
    combat_card: true,
    removed_after_play: true,
    war_status: "1",
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "Michel",
    text:
      ' May only be played after"HL Take Command". Cancels all trench effects fro 1 GE attack and adds a + 1 drm for that attack.',
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "50",
    _id: "cp50",
    ops: "4",
    sr: "4",
    combat_card: true,
    removed_after_play: true,
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "Blucher",
    text:
      ' May only be played after"HL Take Command". Cancels all trench effects for 1 GE attack.',
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "51",
    _id: "cp51",
    ops: "4",
    sr: "4",
    combat_card: true,
    removed_after_play: true,
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "Peace Offensive",
    text:
      ' May only be played after"HL Take Command". Cancels all trench effects for 1 GE attack. If attacker does not advance into the space, subtract 1 VP.',
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "52",
    _id: "cp52",
    ops: "5",
    sr: "5",
    removed_after_play: true,
    rep_ah: "3",
    rep_bu: "1",
    rep_ge: "4",
    rep_tu: "2",
    title: "Fall of the Tsar",
    text:
      ' May only be played if Russian Capitulation marker is in the"Fall of Tsar Allowed"box. Add 1 VP plus an additional 2 VP if RO is still neutral. RU Activation costs 1 OPS per unit, not space, for Combat only.',
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "53",
    _id: "cp53",
    ops: "5",
    sr: "5",
    removed_after_play: true,
    rep_ah: "3",
    rep_bu: "1",
    rep_ge: "4",
    rep_tu: "2",
    title: "Bolshevik Revolution",
    text:
      ' May only be played if Russian Capitulation marker is in the"Bolshevik Revolution Allowed"box. No more than 1 RU RP may be spent each turn.',
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "54",
    _id: "cp54",
    ops: "5",
    sr: "5",
    removed_after_play: true,
    war_status: "2",
    rep_ah: "3",
    rep_bu: "1",
    rep_ge: "4",
    rep_tu: "2",
    title: "H",
    text:
      'L Take Command  Allows play of"Michel","Blucher","Peace Offensive","Hoffman", and"UBoats Unleashed". Prevents play of"Place of Execution".',
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "55",
    _id: "cp55",
    ops: "4",
    sr: "4",
    removed_after_play: true,
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "Lloyd George",
    text:
      "No BR attacks vs. Level 2 entrenched GE units may be made for the rest of this turn. This effect is canceled by play of MICHEL, BLUCHER, or PEACE OFFENSIVE events.",
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "62",
    _id: "cp62",
    ops: "2",
    sr: "2",
    combat_card: true,
    removed_after_play: true,
    rep_ge: "1",
    title: "Achtung: Panzer",
    text: "A GE attack vs. a clear space adds +1 drm.",
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "63",
    _id: "cp63",
    ops: "3",
    sr: "4",
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Russian Desertions",
    text:
      ' May be played after"Fall Of The Tsar".  CP may reduce four 2step RU units.',
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "64",
    _id: "cp64",
    ops: "3",
    sr: "4",
    combat_card: true,
    removed_after_play: true,
    rep_ah: "1",
    rep_ge: "2",
    rep_tu: "1",
    title: "Alberich",
    text:
      ' May not be used if Allies play"Royal Tank Corps"or"Yanks and Tanks".  Cancels any one Allied attack in France/Belgium. Any Allied CC cards are considered not played.',
    deck: "box",
  },
  {
    stage: "total_war",
    side: "cp",
    card_number: "65",
    _id: "cp65",
    ops: "4",
    sr: "4",
    removed_after_play: true,
    rep_ah: "2",
    rep_bu: "1",
    rep_ge: "3",
    rep_tu: "1",
    title: "Prince Max",
    text:
      'May not be played after "HL Take Command"or on or after Turn 13. The"HL Take Command"card is permanently removed from the game. A draw is treated as a CP Victory (including tournament play).',
    deck: "box",
  },
];

module.exports = cp_cards;
